# Use the official Airflow image with Python 3.11
FROM apache/airflow:2.10.2-python3.11

# Switch to root user to install additional software
USER root

# Switch back to the airflow user
USER airflow
